source/_patterns/00-atoms/global/colors.mustache, source/_patterns/00-atoms/text/type-styles.mustache
Shows Primary, Secondary, and Tertiary fonts in available sizes.  Atoms-text-typestyles
Shows Primary and Secondary Colors.  Atoms-global-colors
=> Added Styling to Atoms-text-TypeStyles and Atoms-global-colors

source/_patterns/01-molecules/blocks/carousel-block.mustache, source/_patterns/01-molecules/components/carousel.mustache, source/_patterns/01-molecules/components/slide-2-column.mustache, source/_patterns/02-organisms/sections/hero-carousel.json, source/_patterns/02-organisms/sections/hero-carousel.mustache, source/_patterns/02-organisms/sections/hero-carousel~two-column-169.json, source/_patterns/02-organisms/sections/hero-carousel~two-column.json, source/_patterns/04-pages/home~church.json, source/css/_objects.carousels.scss
@designerbrent Here's a pull request for the two column carousel. Take a look at what I've done here and let me know if you have any questions about anything.
Fixes #11
=> Updating the two column carousel pattern

source/css/styleguide-custom.scss
=> Removing code view from View All pages. 

source/_patterns/02-organisms/content/grid-3up-content.mustache, source/css/_layout.grids.scss
This is based off the news content grid, but a 3 column, instead of 2 column. I need to work out the nth-child rules as I didn't have access to documentation when I created this, but this is a start.
=> NEW: 3 column grid for content. .g-3up-at-medium

source/_data/annotations.js, source/_patterns/00-atoms/global/colors.mustache, source/_patterns/01-molecules/layouts/layout-1-column-fluid.mustache
Adding a single column layout.
=> NEW: 1 column layout

core/styleguide/js/annotations-viewer.js, core/templates/index.mustache, source/css/styleguide-custom.scss
=> Adding hide/show toggle switch for annotations. 

source/_patterns/02-organisms/global/header.mustache, source/_patterns/02-organisms/global/tophat.mustache
The TopHat is now it's own organism for easier management.
=> Moving the TopHat out to it's own organism

source/_data/_data.json, source/_patterns/01-molecules/components/slide.mustache, source/_patterns/02-organisms/sections/hero-carousel~small-format.json
@designerbrent How's about something like this?
Fixes #128
=> Adding new small format carousel option. 

source/_patterns/00-atoms/global/colors.twig
This should resolve the color issues in #189. fixes #189
=> Fixing the color reversal on the secondary colors. 

Gruntfile.js
This will search and replace and instance of `.twig` the contents of each file during the copy process. 
cc/ @reganking
=> Find and replace include file extensions during copy process.

source/_patterns/04-pages/news.twig, source/_patterns/04-pages/news~article-minimal.json
Reverts adventistchurch/alps#186
=> Revert "153 fix news content"

source/css/_base.text.scss
Reference https://github.com/adventistchurch/alps-wordpress/issues/97
=> #97 Problem with quotes

source/_patterns/02-organisms/sections/split-callout@complete.twig
=> Fix to the splitcallout pattern's missing button.

source/_patterns/00-atoms/tables/data-table.twig, source/css/_base.links.scss, source/css/_base.tables.scss
Adds underline to links in table. Closes #232
=> #232 Link colors in tables

.editorconfig
If using VS Code, you'll need [this plugin](https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig).
More info here - http://editorconfig.org/
=> Adding an .editorconfig file

source/css/_base.main.scss, source/css/_modifier.borders.scss
Even spacing to the left and right of the divider. Closed #243
=> #243 Made divider spacing even

source/_data/data.json, source/_patterns/01-molecules/navigation/pagination.twig
The pagination components got missed. This adds them back in.
=> Adding the pagination styles.

source/_patterns/01-molecules/navigation/footer-primary-navigation.twig
As the subject says, this fixes the footer primary links not dimming on hover.
Fixes #315
=> Fixes the footer primary links not dimming on hover. 

source/css/_modifier.colors.scss
=> Removing the !important style declaration on the white color.

source/css/_objects.blocks.scss, source/css/_objects.text.scss
=> #321 Bullets on Share This component

source/_data/data.json, source/_patterns/00-atoms/buttons/button~disabled.json, source/_patterns/00-atoms/buttons/button~lighter.json, source/_patterns/00-atoms/buttons/button~outline.json, source/css/_objects.buttons.scss, source/css/_settings.themes.scss
I have added some additional buttons states as outlined in #312. 
Everything seems to be working with the exception of `:focus` which I need some help to complete.
=> Extra Button states

source/_data/data.json, source/_patterns/01-molecules/navigation/primary-navigation.twig, source/css/_settings.themes.scss
Adding support for `.this-is-active` in the primary and secondary nav areas
Resolves #346
=> #346 support for active links in header nav

source/_patterns/01-molecules/navigation/secondary-navigation.json, source/_patterns/01-molecules/navigation/secondary-navigation.twig, source/_patterns/03-templates/news.twig, source/css/_base.main.scss, source/css/_module.header.scss, source/css/_settings.themes.scss, source/css/_trumps.helper-classes.scss
@designerbrent Once this PR is merged into V3, I'll test in the Wordpress instance to make sure it's working properly. Links to #361
=> Fix for secondary nav dropdowns

.gitignore, .vscode/settings.json, source/js/plugins.js, source/js/script.js
In debugging an issue where a lengthy main menu sometimes overlaps the Sabbath column, I updated the `priorityNav` JS plugin and fixed the way in which it was being used (also removed any app-specific config options from `plugins.js`).
If you’d like, I can remove the `.vscode/settings.json` file and add that directory to the `.gitignore` list.
=> V3 – update priority-navigation JS plugin

source/_patterns/01-molecules/navigation/secondary-navigation.twig, source/css/_module.header.scss
@designerbrent I had to make a few other updates for the dropdown navigation in the secondary menu that needed to made to ALPS PL. Once this PR is merge and deployed to the CDN I will test again to make sure issue `#266` on ALPS WP is fixed.
=> Updated styling for secondary navigation
